#!/usr/bin/env python3

import sys
import unittest
from we import *
from prob import *
from solver import *
from parsing.simple import *
#
class Test_we_element(unittest.TestCase):
    def test_char_repr(self):
        self.assertEqual(str(Character('a')),'C(a)')

    def test_var_repr(self):
        self.assertEqual(str(Variable('var')),'V(var)')

    def test_char_eq(self):
        self.assertTrue(Character('a')==Character('a'))

    def test_var_eq(self):
        self.assertTrue(Variable('a')==Variable('a'))
#
#
class Test_global_functions(unittest.TestCase):
    def test_is_var1(self):
        self.assertTrue(is_var(Variable('var')))

    def test_is_var2(self):
        self.assertFalse(is_var(Character('a')))

    def test_not_var1(self):
        self.assertTrue(not_var(Character('a')))

    def test_not_var2(self):
        self.assertFalse(not_var(Variable('var')))

#
if __name__ == '__main__':
    unittest.main()
